### PR TITLE
Fix scrolling to a fragment now there's a sticky table header

### LINKED ISSUE #370: Direct linking to a statement cuts most of it off
https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/sg/Member_of_the_13th_Parliament#s:md5:941fc0a95448724c4adc9ebb730a2384 for me (on Chrome 67.0.3396.99) goes to:

screen shot 2018-07-26 at 10 55 53

rather than, say:

screen shot 2018-07-26 at 10 55 46

### PR DESCRIPTION
**Pull request by mhl**
Now that there's a sticky header we need to scroll to a different point on the page when someone's navigating to a fragment.

Fixes #370 

screenshot-fragment

### CODE REVIEW

File: app/javascript/app.js [hunk 1]
```diff
@@ -52,7 +52,9 @@ export default template({
       let selector = fragment.replace(/:/g, '\\:')
       let statementRow = document.querySelector(selector)
       if (statementRow) {
+        let headerHeight = document.querySelector('.verification-tool__table th').offsetHeight;
         statementRow.scrollIntoView()
+        window.scrollBy(0, -headerHeight);
```
Comment (zarino) [inline app/javascript/app.js]: If you wanted to, you could do this in one step (without the `scrollIntoView` followed by a `scrollBy`)…

```js
let statementRow = document.querySelector(selector)
let headerRow = document.querySelector('.verification-tool__table th')
if (statementRow) {
  window.scroll({
    top: statementRow.offsetTop - headerRow.offsetHeight
  })
}
```

It’s not much shorter, but maybe it’s simpler?

File: app/javascript/components/statement.js [hunk 2]
```diff
@@ -70,6 +70,12 @@ export default template({
       this.$nextTick( () => {
         this.$emit('search-for', field)
       })
+    },
+    scrollHere: function(event) {
+      let fragment = '#s:' + this.statement.transaction_id;
```
Comment (zarino) [inline app/javascript/components/statement.js]: Feels a bit weird that we’re reconstructing this again here, rather than pulling it out of the `href` attribute of the link we just clicked. Does Vue make the element available via `event.currentTarget` or something similar?

Comment (mhl) [reply app/javascript/components/statement.js]: Good point! It looks like we can use `event.currentTarget.hash`

File: app/javascript/app.js (hunk 1 above)
Comment (mhl) [reply app/javascript/app.js]: Yeah, I like that better - the two scrolls does seem a bit silly.

Comment (mhl) [reply app/javascript/app.js]: Although, as discussed in Slack, `offsetTop` is relative to the parent so now quite the right thing. And the equivalent that works in a good range of browsers is something like:

```
(window.pageYOffset || document.body.scrollTop || document.documentElement.scrollTop) + statementRow.getBoundingClientRect().top - headerRow.offsetHeight
```

... so I think I'll stick with the version with two scrolls since it seems cleaner.
