### PR TITLE
Fix API proxy after changes made for the real API

### LINKED ISSUE #38: fix the MediaWiki API proxy
We discovered there were big mismatches between what the real API and the API proxy were expected - now the code works on the live API, we should update the API proxy to match its behaviour.

### PR DESCRIPTION
**Pull request by gbp**
Having to rename action parameter as this clashes with Rails' action parameter

Closes #38

### CODE REVIEW

File: app/controllers/media_wiki_api_controller.rb [hunk 1]
```diff
@@ -9,12 +9,10 @@ def api_proxy
               'API proxy (Warning: not for use on public installations!)'
       return render(:json => {error: error})
     end
-    action = api_data.delete(:action)
+    action = params[:action_name]
```
Comment (mhl) [inline app/controllers/media_wiki_api_controller.rb]: Wouldn't we want something like `params.require(:action_name)` (and something similar for `:format`) to avoid this warning from Rails?

```
Unpermitted parameters: :format, :action_name
```

(Arguably dealing with `:format` should be in a separate commit, since this was an extant problem.)

Comment (gbp) [reply app/controllers/media_wiki_api_controller.rb]: This warning shouldn't be causing any issues.

In fact if we did switch to using `params.require(:action_name)` then it could prevent us from returning an error on [line 13](https://github.com/mysociety/verification-pages/pull/43/files#diff-ba4e9df56a14344417b69cc2c0d7b036R13).

The `format` is needed for the client side API but not the API proxy as we always are returning JSON so I think we can safely ignore this one too.
