### PR TITLE
Make 'title', not 'position_held_item' the unique column on pages

### LINKED ISSUE #325: Allow more than one Verification Page for a term
In many cases we'll want to combine data from multiple different sources. But when, for example, I tried to create a page for verifying the current term of the Canadian House of Commons from Wikipedia, I got an error:

screen shot 2018-07-20 at 16 09 12

### PR DESCRIPTION
**Pull request by mhl**
It turns out to be useful to be able to create multiple verification
pages, with different sources, for a single term of a particular
parliament. (e.g. you might have one from a scraper of the official
site, and another for a scraper of the Wikipedia page.)

This was being prevented, however, by the Page model having a uniqueness
constraint on 'position_held_item'. This commit changes the uniqueness
constraint on that model to be on 'title' instead. This makes sense
since the rest of the code already treats 'title' as a unique key for
the table (e.g. when the frontend Javascript fetches statements for a
page, it does it using the page title, not the position_held_item.)

Fixes #325

### CODE REVIEW

File: spec/lib/statements_statistics_spec.rb [hunk 1]
```diff
@@ -24,7 +24,7 @@
       ]
       stub_request(:get, 'https://suggestions-store.mysociety.org/export/ca.json')
         .to_return(body: JSON.generate(body))
-      create(:page, position_held_item: 'Q15964890')
+      @page = create(:page, position_held_item: 'Q15964890')
```
Comment (chrismytton) [inline spec/lib/statements_statistics_spec.rb]: I think it would be more consistent with the other specs to use a `let(page) { … }` rather than an instance variable here.

Comment (chrismytton) [reply spec/lib/statements_statistics_spec.rb]: @mhl Ah sorry, that's my fault, I think it needs to be `let!` rather than `let`, as the page needs to exist before `position_stats.pages` is called in the spec.
